language: node_js
node_js:
  - "8"
  - "6"
# Will not be needed once Travis installs this version or higher by default
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.28.1
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - export TZ=Europe/Madrid
script: npm run travis
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
cache:
  yarn: true
