language: node_js
node_js:
  - "8"
  - "6"
before_install:
  - npm -g install yarn@^0.28.0
  - yarn config set workspaces-experimental true
before_script:
  - export TZ=Europe/Madrid
script: npm run travis
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
cache:
  directories:
    - ~/.yarn
    - ~/.nvm
