environment:
  matrix:
    #- nodejs_version: "4"
    - nodejs_version: "6"

version: 1.0.{build}

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - yarn --version
  - yarn

cache:
  - node_modules
  - .eslintcache

build:
  verbosity: minimal

build_script: npm run travis
